--DROP TABLE IF EXISTS tickers;
--DROP TABLE IF EXISTS trades;

CREATE TABLE tickers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ticker TEXT NOT NULL,
  is_synthetic INTEGER NOT NULL
);

CREATE TABLE trades (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tid INTEGER NOT NULL,
  ticker_id INTEGER NOT NULL,
  date_ INTEGER NOT NULL,
  price DECIMAL NOT NULL,
  amount DECIMAL NOT NULL,
  FOREIGN KEY(ticker_id) REFERENCES tickers(id)
);
